# Generated by Django 4.0 on 2022-01-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='msgreq',
        ),
    ]
