# Generated by Django 4.0 on 2022-01-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_front', '0002_rename_contact_msgreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgreq',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
